apiVersion: v1
kind: Service
metadata:
  name: adaptmem
  labels:
    app: adaptmem
spec:
  type: ClusterIP
  selector:
    app: adaptmem
  ports:
    - name: http
      port: 7800
      targetPort: http
      protocol: TCP
